# This file was generated by GoReleaser. DO NOT EDIT.
class GoreleaserWork < Formula
  desc "show version info only."
  homepage "https://github.com/reiki4040/goreleaser-work"
  version "0.1.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/reiki4040/goreleaser-work/releases/download/v0.1.0/goreleaser-work_darwin_x86_64.tar.gz"
    sha256 "4f8963b81c2d841ce01d1d6c9c1933f0ff93f955bedf3dfccb044f8de6bd48a9"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/reiki4040/goreleaser-work/releases/download/v0.1.0/goreleaser-work_linux_x86_64.tar.gz"
      sha256 "09e8e7acfffbb1b683f68b3c06ff1060bca2a2f0ffbb595ac082f741e01e7c4c"
    end
  end

  def install
    bin.install "goreleaser-work"
  end

  def caveats; <<~EOS
    this message is shown on console when finished install with homebrew.
  EOS
  end
end
