project_name: goreleaser-work
env:
  - GO111MODULE=on
before:
  hooks:
    - go mod tidy
builds:
  - main: .
    binary:
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.revision={{.ShortCommit}}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
archives:
  - name_template: >-
      {{ .ProjectName }}_
      {{- .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else }}{{ .Arch }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip
release:
  prerelease: auto
  
# homebrew
brews:
  - description: "show version info only."
    tap:
      owner: reiki4040
      name: homebrew-tap
      token: "{{ .Env.GH_PAT }}"
    homepage: "https://github.com/reiki4040/goreleaser-work"
    install: |
      bin.install "goreleaser-work"
    caveats: |
      this message is shown on console when finished install with homebrew.
