# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GoreleaserWork < Formula
  desc "show version info only."
  homepage "https://github.com/reiki4040/goreleaser-work"
  version "0.2.0"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/reiki4040/goreleaser-work/releases/download/v0.2.0/goreleaser-work_darwin_x86_64.tar.gz"
    sha256 "194bd8ecd81f9f68d8bd3a28d8ea663bf09570859aee6e40b6527a57fe3072d5"
  end
  if OS.mac? && Hardware::CPU.arm?
    url "https://github.com/reiki4040/goreleaser-work/releases/download/v0.2.0/goreleaser-work_darwin_arm64.tar.gz"
    sha256 "1d6dc82ece6eaec87fe5cee0f67b33e07f02e02279450249974476e4b9bc0199"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/reiki4040/goreleaser-work/releases/download/v0.2.0/goreleaser-work_linux_x86_64.tar.gz"
    sha256 "1de8a805ed685f699009a7c143f4af4ef325f336313f43a27388ca6fbaed0231"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/reiki4040/goreleaser-work/releases/download/v0.2.0/goreleaser-work_linux_arm64.tar.gz"
    sha256 "45d27cdb0ad381e5e51823c551136873ad84190f47338476e2bd82d1e2eba74b"
  end

  def install
    bin.install "goreleaser-work"
  end

  def caveats; <<~EOS
    this message is shown on console when finished install with homebrew.
  EOS
  end
end
